id: I4AC1B1B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:01:36+00:00'
last_modified: '2022-06-07T17:47:14.959880+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD211
  title: འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    169B:
      image_group_id: I4PD269
      title: ''
      total_pages: 790
      order: 1
      base_file: 169B.txt
    B89F:
      image_group_id: I4PD270
      title: ''
      total_pages: 806
      order: 2
      base_file: B89F.txt
    D1C0:
      image_group_id: I4PD271
      title: ''
      total_pages: 790
      order: 3
      base_file: D1C0.txt
    52D5:
      image_group_id: I4PD272
      title: ''
      total_pages: 762
      order: 4
      base_file: 52D5.txt
    25C3:
      image_group_id: I4PD273
      title: ''
      total_pages: 792
      order: 5
      base_file: 25C3.txt
    0E77:
      image_group_id: I4PD274
      title: ''
      total_pages: 766
      order: 6
      base_file: 0E77.txt
    EF5E:
      image_group_id: I4PD275
      title: ''
      total_pages: 798
      order: 7
      base_file: EF5E.txt
    BBE2:
      image_group_id: I4PD276
      title: ''
      total_pages: 800
      order: 8
      base_file: BBE2.txt
    2FEB:
      image_group_id: I4PD277
      title: ''
      total_pages: 770
      order: 9
      base_file: 2FEB.txt
    A22A:
      image_group_id: I4PD278
      title: ''
      total_pages: 776
      order: 10
      base_file: A22A.txt
    E10D:
      image_group_id: I4PD279
      title: ''
      total_pages: 824
      order: 11
      base_file: E10D.txt
    4A42:
      image_group_id: I4PD280
      title: ''
      total_pages: 796
      order: 12
      base_file: 4A42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
