id: I4AC1B1B4
legacy_id: P003128
ocr_import_info:
  bdrc_scan_id: W4PD211
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T09:53:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:25:29.200720+00:00'
last_modified: 2022-09-04 05:30:32.033940
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD211
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4PD211
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབུམ།
statistics:
  ocr_word_mean_confidence_index: 0.602625612420933
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I4PD271:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD271
      total_pages: 790
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD271.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.613853682054694
    legacy_id: v003
  I4PD272:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD272
      total_pages: 762
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD272.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5944457287699344
    legacy_id: v004
  I4PD276:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD276
      total_pages: 800
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD276.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5997236655484413
    legacy_id: v008
  I4PD273:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD273
      total_pages: 792
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD273.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6417532179155192
    legacy_id: v005
  I4PD278:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD278
      total_pages: 776
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4PD278.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5797682177421947
    legacy_id: v010
  I4PD274:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD274
      total_pages: 766
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD274.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6131340258123372
    legacy_id: v006
  I4PD275:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD275
      total_pages: 798
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD275.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6407337254107349
    legacy_id: v007
  I4PD269:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD269
      total_pages: 790
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD269.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5995199589898825
    legacy_id: v001
  I4PD280:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD280
      total_pages: 796
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I4PD280.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5640589755859754
    legacy_id: v012
  I4PD279:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD279
      total_pages: 824
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I4PD279.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5794118382266045
    legacy_id: v011
  I4PD270:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD270
      total_pages: 806
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD270.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6074528358954451
    legacy_id: v002
  I4PD277:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD277
      total_pages: 770
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4PD277.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5921737335138679
    legacy_id: v009
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
