id: P003128
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:42:13.124412
source_metadata:
  id: bdr:W4PD211
  title: འབུམ།
  author: ''
  volumes:
    dbd764c05a0548318cc399d4ae411fd9:
      image_group_id: I4PD269
      title: ''
      volume_number: 1
      total_pages: 790
      base_file: v001.txt
    033b0aeec3794d55ac61ddf13381123a:
      image_group_id: I4PD270
      title: ''
      volume_number: 2
      total_pages: 806
      base_file: v002.txt
    44df50065e344d4ea2c8f6933540fb71:
      image_group_id: I4PD271
      title: ''
      volume_number: 3
      total_pages: 790
      base_file: v003.txt
    e27bafa5a66440feb4abef7bc3db914e:
      image_group_id: I4PD272
      title: ''
      volume_number: 4
      total_pages: 762
      base_file: v004.txt
    13a52a19bb7649dc896ac1e03719d440:
      image_group_id: I4PD273
      title: ''
      volume_number: 5
      total_pages: 792
      base_file: v005.txt
    3b82b3239d6d403d81124f656b281ccb:
      image_group_id: I4PD274
      title: ''
      volume_number: 6
      total_pages: 766
      base_file: v006.txt
    033d589785db4a659915366457b98dc2:
      image_group_id: I4PD275
      title: ''
      volume_number: 7
      total_pages: 798
      base_file: v007.txt
    c61bab3c65e54f1e945f9379677448d6:
      image_group_id: I4PD276
      title: ''
      volume_number: 8
      total_pages: 800
      base_file: v008.txt
    71a4d09227bc441eafec557a4e74c21c:
      image_group_id: I4PD277
      title: ''
      volume_number: 9
      total_pages: 770
      base_file: v009.txt
    a836c8d6a5a1422aa4519f76c59caf11:
      image_group_id: I4PD278
      title: ''
      volume_number: 10
      total_pages: 776
      base_file: v010.txt
    c4bddec8f50042138cd3ee7db9266265:
      image_group_id: I4PD279
      title: ''
      volume_number: 11
      total_pages: 824
      base_file: v011.txt
    ff0dc3a6897b4ca4a809029b0f09941f:
      image_group_id: I4PD280
      title: ''
      volume_number: 12
      total_pages: 796
      base_file: v012.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
